### ISSUE TITLE
getDeparturesFromStopPlaces fails with GraphQL exception

### ISSUE THREAD

**Issue by torfjor** [entur/sdk#127]
Hi.

The above-mentioned method throws: `"GraphQL: Exception while fetching data (/stopPlaces[0]/estimatedCalls) : null",`

I managed to make this query fail in GraphiQL too: [Link](https://api.entur.io/journey-planner/v2/ide/?query=query%20(%24ids%3A%20%5BString%5D!%2C%20%24start%3A%20DateTime!%2C%20%24timeRange%3A%20Int!%2C%20%24limit%3A%20Int!%2C%20%24limitPerLine%3A%20Int%2C%20%24omitNonBoarding%3A%20Boolean!%2C%20%24whiteListedLines%3A%20%5BString!%5D%2C%20%24whiteListedAuthorities%3A%20%5BString!%5D%2C%20%24whiteListedModes%3A%20%5BMode%5D%2C%20%24includeCancelledTrips%3A%20Boolean)%20%7B%0A%20%20stopPlaces(ids%3A%20%24ids)%20%7B%0A%20%20%20%20id%0A%20%20%20%20estimatedCalls(startTime%3A%20%24start%2C%20timeRange%3A%20%24timeRange%2C%20numberOfDepartures%3A%20%24limit%2C%20numberOfDeparturesPerLineAndDestinationDisplay%3A%20%24limitPerLine%2C%20omitNonBoarding%3A%20%24omitNonBoarding%2C%20whiteListed%3A%20%7Blines%3A%20%24whiteListedLines%2C%20authorities%3A%20%24whiteListedAuthorities%7D%2C%20whiteListedModes%3A%20%24whiteListedModes%2C%20includeCancelledTrips%3A%20%24includeCancelledTrips)%20%7B%0A%20%20%20%20%20%20...estimatedCallFields%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A%0Afragment%20estimatedCallFields%20on%20EstimatedCall%20%7B%0A%20%20actualArrivalTime%0A%20%20actualDepartureTime%0A%20%20aimedArrivalTime%0A%20%20aimedDepartureTime%0A%20%20cancellation%0A%20%20date%0A%20%20destinationDisplay%20%7B%0A%20%20%20%20frontText%0A%20%20%7D%0A%20%20expectedDepartureTime%0A%20%20expectedArrivalTime%0A%20%20forAlighting%0A%20%20forBoarding%0A%20%20notices%20%7B%0A%20%20%20%20...noticeFields%0A%20%20%7D%0A%20%20quay%20%7B%0A%20%20%20%20...quayFields%0A%20%20%7D%0A%20%20realtime%0A%20%20requestStop%0A%20%20serviceJourney%20%7B%0A%20%20%20%20...serviceJourneyFields%0A%20%20%7D%0A%20%20situations%20%7B%0A%20%20%20%20...situationFields%0A%20%20%7D%0A%7D%0A%0Afragment%20noticeFields%20on%20Notice%20%7B%0A%20%20text%0A%7D%0A%0Afragment%20quayFields%20on%20Quay%20%7B%0A%20%20id%0A%20%20name%0A%20%20description%0A%20%20publicCode%0A%20%20situations%20%7B%0A%20%20%20%20...situationFields%0A%20%20%7D%0A%20%20stopPlace%20%7B%0A%20%20%20%20...stopPlaceFields%0A%20%20%7D%0A%7D%0A%0Afragment%20situationFields%20on%20PtSituationElement%20%7B%0A%20%20situationNumber%0A%20%20summary%20%7B%0A%20%20%20%20language%0A%20%20%20%20value%0A%20%20%7D%0A%20%20description%20%7B%0A%20%20%20%20language%0A%20%20%20%20value%0A%20%20%7D%0A%20%20detail%20%7B%0A%20%20%20%20language%0A%20%20%20%20value%0A%20%20%7D%0A%20%20lines%20%7B%0A%20%20%20%20...lineFields%0A%20%20%7D%0A%20%20validityPeriod%20%7B%0A%20%20%20%20startTime%0A%20%20%20%20endTime%0A%20%20%7D%0A%20%20reportType%0A%20%20infoLinks%20%7B%0A%20%20%20%20uri%0A%20%20%20%20label%0A%20%20%7D%0A%7D%0A%0Afragment%20lineFields%20on%20Line%20%7B%0A%20%20bookingArrangements%20%7B%0A%20%20%20%20...bookingArrangementFields%0A%20%20%7D%0A%20%20description%0A%20%20flexibleLineType%0A%20%20id%0A%20%20name%0A%20%20notices%20%7B%0A%20%20%20%20...noticeFields%0A%20%20%7D%0A%20%20publicCode%0A%20%20transportMode%0A%20%20transportSubmode%0A%7D%0A%0Afragment%20bookingArrangementFields%20on%20BookingArrangement%20%7B%0A%20%20bookingMethods%0A%20%20bookingNote%0A%20%20minimumBookingPeriod%0A%20%20bookingContact%20%7B%0A%20%20%20%20phone%0A%20%20%20%20url%0A%20%20%7D%0A%7D%0A%0Afragment%20stopPlaceFields%20on%20StopPlace%20%7B%0A%20%20id%0A%20%20description%0A%20%20name%0A%20%20tariffZones%20%7B%0A%20%20%20%20id%0A%20%20%7D%0A%7D%0A%0Afragment%20serviceJourneyFields%20on%20ServiceJourney%20%7B%0A%20%20id%0A%20%20journeyPattern%20%7B%0A%20%20%20%20line%20%7B%0A%20%20%20%20%20%20...lineFields%0A%20%20%20%20%7D%0A%20%20%20%20notices%20%7B%0A%20%20%20%20%20%20...noticeFields%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20notices%20%7B%0A%20%20%20%20...noticeFields%0A%20%20%7D%0A%20%20publicCode%0A%20%20transportSubmode%0A%7D%0A%0A&variables=%7B%0A%20%20%22ids%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22NSR%3AStopPlace%3A43292%22%0A%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%22start%22%3A%20%222020-01-28T11%3A10%3A22.706Z%22%2C%0A%20%20%20%20%20%20%20%20%22timeRange%22%3A%203600%2C%0A%20%20%20%20%20%20%20%20%22limit%22%3A%2010%2C%0A%20%20%20%20%20%20%20%20%22omitNonBoarding%22%3A%20false%0A%7D)

Will you have a look?

**Comment by draperunner** [comment]
I'll take a look. Thanks!

**Comment by draperunner** [comment]
It fails because the `includeCancelledTrips` parameter is undefined. I'll add a default value of `false`, but a quickfix now is just to add `includeCancelledTrips: false` to the options for getDeparturesFromStopPlaces.

**Comment by draperunner** [comment]
Fixed in next-52 and 1.0.0
