### ISSUE TITLE
Leg-mode information missing from getTripPatterns docs

### ISSUE THREAD

**Issue by poacher2k** [entur/sdk#177]
The "Array of Modes"-link doesn't go to anywhere, as the information seems to be missing @ https://github.com/entur/sdk/blob/master/docs/travel/getTripPatterns.mdx#leg-mode

![image](https://user-images.githubusercontent.com/2255960/97103430-c0d06180-16ac-11eb-8720-f0afa3d65863.png)

**Comment by draperunner** [comment]
Hi! Thanks for the report. Most of the type links are dead, I'm afraid. The [TypeScript libdef](https://github.com/entur/sdk/blob/master/index.d.ts) is your best reference for now, until we fix the docs.
