### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by J3551c9** [entur/sdk#19]
Hi, I´m trying to run the examples but I always get, do you have any idea about what I´m doing wrong? 

Thanks! 
The Code:
const { default: EnturService, convertLocationToPosition } = require('../lib')

const service = new EnturService({ clientName: 'tjruterapp-ruterapp'})

async function example() {
    const [fromLocation] = await service.getLocations('Ryllikvegen, Lillehammer')
    const [toLocation] = await service.getLocations('Oslo S')

    if (fromLocation && toLocation) {
        service.getTripPatterns({
            searchDate: new Date(),
            from: convertLocationToPosition(fromLocation),
            to: convertLocationToPosition(toLocation),
        }).then(console.log) // eslint-disable-line no-console
    }
}
The error:
example()(node:80207) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by draperunner** [comment]
Hi!

In what environment are you running your program? Currently, we only support running in a browser –not in Node.js.

Could you try adding a `.catch` block and print the actual error that occurs? I suspect the error is `ReferenceError: fetch is not defined`.

```
if (fromLocation && toLocation) {
    service.getTripPatterns({
        searchDate: new Date(),
        from: convertLocationToPosition(fromLocation),
        to: convertLocationToPosition(toLocation),
    }).then(console.log) // eslint-disable-line no-console
    .catch(console.error)
}
```

**Comment by J3551c9** [comment]
Ohh I see, I was making the call from node.  
I also tried Curl but I got Internal Server Error 500

curl -X POST -H "et-client-name: justadev-ruterapp" -d ' { "query": "query{trip(from: {place:\"NSR:StopPlace:14115\"}, to: {place: \"NSR:StopPlace:12655\"}, modes:[bus], maximumTransfers:0, numTripPatterns:20) {tripPatterns { startTime endTime walkDistance legs { mode distance line { id publicCode } } } } } "}' https://api.entur.org/journeyplanner/2.0/index/graphql

**Comment by draperunner** [comment]
@J3551c9 To get your curl request to work, add the `Content-Type: application/json` header, and make sure to escape your inner quotes:

`curl -X POST -H "et-client-name: justadev-ruterapp" -H 'content-type: application/json' -d ' { "query": "query{trip(from: {place:\"NSR:StopPlace:14115\"}, to: {place: \"NSR:StopPlace:12655\"}, modes:[bus], maximumTransfers:0, numTripPatterns:20) {tripPatterns { startTime endTime walkDistance legs { mode distance line { id publicCode } } } } } "}' https://api.entur.org/journeyplanner/2.0/index/graphql`

I will post here when Node support has been added. :)

**Comment by J3551c9** [comment]
thanks @draperunner

**Comment by draperunner** [comment]
Version 0.5.0 is now released, which supports Node.js. https://github.com/entur/sdk/releases/tag/v0.5.0
