### ISSUE TITLE
TypeError on no results in getTripPatterns

### ISSUE THREAD

**Issue by aleksandervines** [entur/sdk#21]
Hi,

It seems like you are producing a _TypeError_ in _getTripPatterns_ if the response from the API is empty (i.e. no results found).

It seems like a bug to me, I'd expect to either get a more meaningful error or perhaps just an empty array back.

TypeError: Cannot read property 'trip' of undefined
    at @entur\sdk\lib\trip\index.js:69:26

On a sidenote, I love the fact that you have made this javascript library to access your API. 

Cheers,
Aleksander

**Comment by draperunner** [comment]
Hi! Thanks for reporting this. I have investigated the issue, and you're right: A TypeError is produced when no results are found. We should return an empty array. I'll open a PR soon to fix this.

Glad you like the SDK!

**Comment by draperunner** [comment]
v0.5.1 is now released, which fixes this issue. https://github.com/entur/sdk/releases/tag/v0.5.1
