### ISSUE TITLE
Are the examples outdated?

### ISSUE THREAD

**Issue by nixolas1** [entur/sdk#48]
The examples on the master branch say
```
service.getTripPatterns({
    searchDate: new Date(),
    from: {
        name: 'Ryllikvegen, Lillehammer',
        coordinates: {
            latitude: 61.102848368937416,
            longitude: 10.51613308426234
        },
    },
    to: {
        place: 'NSR:StopPlace:337',
        name: 'Oslo S, Oslo'
    }
})
```

but when installing the package i get `@entur/sdk@1.0.0-next.4`, which defines getTripPatterns like this:
```  
getTripPatterns(
      from: Location,
      to: Location,
      params?: GetTripPatternsParams,
      ignoreFields?: Array<string>,
  ): Promise<TripPattern[]>;
```
 Should the examples be updated, or have a notice saying that the default installed package is "next", and may not work like the examples?

Cheers!

**Comment by draperunner** [comment]
Yes, you're right. The `1.0.0-next.x` versions are still experimental with lots of breaking changes. The docs in the README refer to v0.10.3, and I would recommend you to install that version. 

I'll add a note to the README to clarify, and we'll of course update the docs when v1.0.0 is tested and ready.

Thanks for pointing this out!
