### ISSUE TITLE
Name er ikke required i Location

### ISSUE THREAD

**Issue by FredrikMeyer** [entur/sdk#59]
Burde vært en ? foran name i https://github.com/entur/sdk/blob/v1.0.0-next.12/flow-types/Location.js fordi navn ikke er påkrevd i GraphQL-interfacet.

https://github.com/entur/sdk/blob/95b4113b7995d3f96c67eed86fae2d4249fda399/flow-types/Location.js#L5

**Comment by draperunner** [comment]
Fixed by https://github.com/entur/sdk/pull/63
